version: '3.8'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server
    restart: unless-stopped
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ollama-data:/root/.ollama
    entrypoint: ["/bin/sh", "-c", "
      ollama serve & sleep 10 &&
      if ! ollama list | grep -q deepseek; then ollama pull deepseek:7b; fi &&
      tail -f /dev/null"]

volumes:
  ollama-data:
